"""Generates packaging/THIRD_PARTY_NOTICES.md from the metadata of the packages bundled in the app.

    py -3.11 packaging\\notices.py            writes packaging\\THIRD_PARTY_NOTICES.md
    py -3.11 packaging\\notices.py --check    lists the bundled packages, fails if a root is missing

The roots are the app's runtime dependencies listed in requirements.txt; their own dependencies
are followed automatically. PyInstaller is added because its bootloader is part of OwlOCR.exe.
Run it with the build venv (build\\venv), so that only the bundled packages are listed.
"""
from __future__ import annotations

import importlib.metadata as md
import re
import sys
from pathlib import Path

from packaging.requirements import Requirement

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "packaging" / "THIRD_PARTY_NOTICES.md"
REQUIREMENTS = REPO / "requirements.txt"
EXTRA = ("pyinstaller",)       # its bootloader is part of OwlOCR.exe; its own dependencies are not
# Summary corrections where the package metadata is missing or misleading (keys: normalised names).
LICENSE_OVERRIDES = {
    "pyinstaller": "GPLv2 with bootloader exception (only the bootloader is included)",
    "clr-loader": "MIT",        # the metadata has no licence field; its LICENSE file is MIT
}
SOURCE_OVERRIDES = {
    "charset-normalizer": "https://github.com/jawah/charset_normalizer",
}
ENGINE_ONLY = ("torch", "torchvision", "transformers", "tokenizers", "safetensors", "accelerate")
# Bundled files that are not Python packages: (name, version, licence, licence file in the repo).
FONTS = (("DejaVu Sans", "2.37", "Bitstream Vera Fonts licence and public domain (DejaVu changes)",
          "owlocr/export/fonts/DejaVuSans-LICENSE.txt"),)
# Components shipped inside a package's files, without a licence text of their own in the package.
OTHER_BUNDLED = (
    ("Microsoft Edge WebView2 SDK",
     "`Microsoft.Web.WebView2.Core.dll`, `Microsoft.Web.WebView2.WinForms.dll` and `WebView2Loader.dll`, "
     "shipped inside pywebview. Copyright Microsoft Corporation. Licence: see "
     "https://www.nuget.org/packages/Microsoft.Web.WebView2"),
    (".NET facade assemblies",
     "`System.*.dll` and `netstandard.dll`, shipped inside pythonnet. MIT License, .NET Foundation and "
     "contributors: https://github.com/dotnet/runtime/blob/main/LICENSE.TXT"),
)
LICENSE_FILE = re.compile(r"\.dist-info/(licenses/.+|[^/]*(LICEN[CS]E|COPYING|NOTICE|AUTHORS)[^/]*)$", re.I)

HEADER = """# Third-party notices

Owl OCR is released under the MIT License (see `LICENSE`). The installer and the portable zip
contain the third-party software listed below. This file is generated by
`packaging/notices.py` from the metadata of the installed packages; do not edit it by hand.
"""

ENGINE_SECTION = """## Downloaded by the setup wizard (not part of the installer)

- **Unlimited-OCR model** by Baidu (https://huggingface.co/baidu/Unlimited-OCR, revision
  07dea832e22aefee32ad281d4b80551282e1c168): MIT License. The file `modeling_deepseekv2.py`
  (Copyright 2023 DeepSeek-AI and The HuggingFace Inc. team) is under the Apache License,
  Version 2.0; its text is in `licenses/Apache-2.0.txt` and, after installation, in the model
  folder as `LICENSE-Apache-2.0.txt`. On computers that read with the processor Owl OCR modifies
  `modeling_unlimitedocr.py`; the modified file says so in its first lines and the original is
  kept as `modeling_unlimitedocr.py.orig`.
- **Spell-check dictionaries** (optional, downloaded only when the user asks, from the
  LibreOffice dictionaries project at pinned commits, see `owlocr/pipeline/dictionaries.json`):
  Czech `cs_CZ` under the GNU GPL, English `en_US` under the SCOWL licence. Each is stored
  unmodified together with its licence text in the dictionaries folder of the data root.
- **uv** by Astral (Apache-2.0 or MIT), **CPython 3.11** (PSF License), **PyTorch** (BSD-3-Clause),
  **transformers** (Apache-2.0) and the other packages in `worker/requirements-engine.txt` are
  installed from their official sources into the separate engine folder, each with its own
  licence files.
"""


def norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def roots_from_requirements(path: Path = REQUIREMENTS) -> tuple[str, ...]:
    """Package names of a requirements file; `-r` includes, options and comments are skipped."""
    roots = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if line and not line.startswith("-"):
            roots.append(Requirement(line).name)
    bad = [r for r in roots if norm(r) in ENGINE_ONLY]
    if bad:
        raise ValueError(f"engine packages must not be app requirements: {bad}")
    return tuple(roots)


def closure(roots: tuple[str, ...], extra: tuple[str, ...] = ()) -> list[md.Distribution]:
    seen: dict[str, md.Distribution] = {}
    pending = list(roots)
    while pending:
        name = norm(pending.pop())
        if name in seen:
            continue
        dist = md.distribution(name)
        seen[name] = dist
        for line in dist.requires or []:
            req = Requirement(line)
            if req.marker is not None and not req.marker.evaluate({"extra": ""}):
                continue
            pending.append(req.name)
    for name in extra:
        seen.setdefault(norm(name), md.distribution(name))
    return sorted(seen.values(), key=lambda d: norm(d.metadata["Name"]))


def license_texts(dist: md.Distribution) -> list[tuple[str, str]]:
    texts = []
    for f in dist.files or []:
        rel = str(f).replace("\\", "/")
        if LICENSE_FILE.search(rel):
            try:
                texts.append((rel.rsplit("/", 1)[-1], Path(dist.locate_file(f)).read_text(encoding="utf-8", errors="replace")))
            except OSError:
                pass
    if not texts:
        long_text = (dist.metadata.get("License") or "").strip()
        if "\n" in long_text:
            texts.append(("License (from package metadata)", long_text))
    return texts


def license_name(dist: md.Distribution) -> str:
    meta = dist.metadata
    override = LICENSE_OVERRIDES.get(norm(meta["Name"]))
    if override:
        return override
    if meta.get("License-Expression"):
        return meta["License-Expression"].strip()
    classifiers = [c.split(" :: ")[-1] for c in (meta.get_all("Classifier") or []) if c.startswith("License ::")]
    if classifiers:
        return ", ".join(dict.fromkeys(classifiers))
    short = (meta.get("License") or "").strip()
    if short and "\n" not in short and len(short) <= 80:
        return short
    return "see the licence text below"


def source_url(dist: md.Distribution) -> str:
    """Where the source can be had: first Source/Homepage/Repository Project-URL, else Home-page, else a dash."""
    override = SOURCE_OVERRIDES.get(norm(dist.metadata["Name"]))
    if override:
        return override
    urls = {}
    for entry in dist.metadata.get_all("Project-URL") or []:
        label, _, url = entry.partition(",")
        urls.setdefault(label.strip().lower(), url.strip())
    for label in ("source", "homepage", "repository"):
        for key, url in urls.items():
            if key.startswith(label) and url:
                return url
    home = (dist.metadata.get("Home-page") or "").strip()
    return home or "–"


def python_license() -> str:
    path = Path(sys.base_prefix) / "LICENSE.txt"
    return path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""


def font_notices(root: Path = REPO) -> list[tuple[str, str, str, str]]:
    """(name, version, licence, licence text) of every bundled font."""
    return [(name, version, licence, (root / rel).read_text(encoding="utf-8", errors="replace"))
            for name, version, licence, rel in FONTS]


def render(dists: list[md.Distribution], python_text: str,
           fonts: list[tuple[str, str, str, str]] | tuple = ()) -> str:
    lines = [HEADER, "## Summary", "", "| Package | Version | Licence | Source |", "|---|---|---|---|"]
    lines.append(f"| Python | {sys.version.split()[0]} | PSF License | https://www.python.org |")
    for d in dists:
        lines.append(f"| {d.metadata['Name']} | {d.version} | {license_name(d)} | {source_url(d)} |")
    for name, version, licence, _text in fonts:
        lines.append(f"| {name} (font) | {version} | {licence} | https://dejavu-fonts.github.io |")
    lines += ["", "## Other bundled components", "",
              "These files are shipped inside the packages above. Their licence text is not part of "
              "the installed packages, so only the licence location is given here.", ""]
    for name, text in OTHER_BUNDLED:
        lines.append(f"- **{name}**: {text}")
    lines += ["", ENGINE_SECTION, "## Licence texts", ""]
    if python_text:
        lines += [f"### Python {sys.version.split()[0]}", "", "````text", python_text.strip(), "````", ""]
    for name, version, _licence, text in fonts:
        lines += [f"### {name} {version} (font)", "", "````text", text.strip(), "````", ""]
    for d in dists:
        lines += [f"### {d.metadata['Name']} {d.version}", ""]
        texts = license_texts(d)
        if not texts:
            author = (d.metadata.get("Author") or "").strip()
            by = f" (author: {author})" if author else ""
            lines += [f"Licence: {license_name(d)}, stated in the package metadata{by}. "
                      "The package ships no licence file.", ""]
        for title, text in texts:
            lines += [f"`{title}`", "", "````text", text.strip(), "````", ""]
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    try:
        dists = closure(roots_from_requirements(), EXTRA)
    except md.PackageNotFoundError as exc:
        print(f"MISSING: {exc}. Install the app requirements into this Python first.")
        return 1
    if "--check" in argv:
        for d in dists:
            print(f"{d.metadata['Name']}=={d.version}  [{license_name(d)}]")
        return 0
    OUT.write_text(render(dists, python_license(), font_notices()), encoding="utf-8")
    print(f"{len(dists)} packages written to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
